highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://csqlwang.github.io/homepage/
author: FÃ¡bio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /homepage/
title: Homepage of Qilong Wang
name: Qilong Wang
email: qlwang@tju.edu.cn
email_full: mailto:qlwang@tju.edu.cn
website: github.com/csqlwang
website_full: https://github.com/csqlwang

address:
  street: 135 Yaguan Road
  postcode: 300350
  city: Tianjin
  country: China

# needed for travis-ci build
exclude: [vendor]
